### PR TITLE
use getShareDir as an indicator of Symfony version

### LINKED ISSUE #4719: build(ContainerBuilder $container) incompatibility (Symfony 8, php 8.4)
Running php 8.4 and Symfony 8 (include symfony/twig-bundle) I'm getting this error.

The issue is with

Did something change in Symfony 8 so that this if statement needs to change?

```php
if (!method_exists(ContainerBuilder::class, 'getAutoconfiguredAttributes')) {
    class TwigExtraBundle extends Bundle
    {
        public function build(ContainerBuilder $container): void
        {
            parent::build($container);

            $container->addCompilerPass(new MissingExtensionSuggestorPass());
        }
    }
} else {
    class TwigExtraBundle extends Bundle
    {
        /** @return void */
        public function build(ContainerBuilder $container)
        {
```

m var/cache/ -rf
~/g/sites/md$ bin/console c:cl
PHP Fatal error:  Declaration of Twig\Extra\TwigExtraBundle\TwigExtraBundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container) must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container): void in /home/tac/g/sites/md/vendor/twig/extra-bundle/TwigExtraBundle.php on line 32
Symfony\Component\ErrorHandler\Error\FatalError^ {#90
  #message: "Compile Error: Declaration of Twig\Extra\TwigExtraBundle\TwigExtraBundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container) must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container): void"
  #code: 0
  #file: "./vendor/twig/extra-bundle/TwigExtraBundle.php"
  #line: 32
  -error: array:4 [
    "type" => 64
    "message" => "Declaration of Twig\Extra\TwigExtraBundle\TwigExtraBundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container) must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::build(Symfony\Component\DependencyInjection\ContainerBuilder $container): void"
    "file" => "/home/tac/g/sites/md/vendor/twig/extra-bundle/TwigExtraBundle.php"
    "line" => 32
  ]
}

### PR DESCRIPTION
**Pull request by tacman**
Proposal to fix #4719 , replaces #4721

### CODE REVIEW

File: extra/twig-extra-bundle/TwigExtraBundle.php [hunk 1]
```diff
@@ -13,9 +13,10 @@
 
 use Symfony\Component\DependencyInjection\ContainerBuilder;
 use Symfony\Component\HttpKernel\Bundle\Bundle;
+use Symfony\Component\HttpKernel\KernelInterface;
 use Twig\Extra\TwigExtraBundle\DependencyInjection\Compiler\MissingExtensionSuggestorPass;
 
-if (!method_exists(ContainerBuilder::class, 'getAutoconfiguredAttributes')) {
+if (!method_exists(KernelInterface::class, 'getShareDir')) {
```
Comment (nicolas-grekas) [inline extra/twig-extra-bundle/TwigExtraBundle.php]:
```suggestion
if (method_exists(KernelInterface::class, 'getShareDir')) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tacman.
