### PR TITLE
Fix twig_compare float-string trailing whitespace + refactor

### LINKED ISSUE #3345: 3.0 regression/inconsistency when comparing a float to a numeric string with trailing space
This is a proper bug report for PR #3256.

Code sample:

```twig
{{ 42 == '42' ? '.' : 'F' -}}
{{ '42' == 42 ? '.' : 'F' -}}
{{ 42 == ' 42' ? '.' : 'F' -}}
{{ ' 42' == 42 ? '.' : 'F' -}}
{{ 42 == '42 ' ? '.' : 'F' -}}
{{ '42 ' == 42 ? '.' : 'F' -}}
{{ 42.0 == '42.0' ? '.' : 'F' -}}
{{ '42.0' == 42.0 ? '.' : 'F' -}}
{{ 42.0 == ' 42.0' ? '.' : 'F' -}}
{{ ' 42.0' == 42.0 ? '.' : 'F' -}}
{{ 42.0 == '42.0 ' ? '.' : 'F' -}}
{{ '42.0 ' == 42.0 ? '.' : 'F' -}}
```

Output in v1.42.0 and v2.12.5:
`............`

Output in v3.0.3:
`..........FF`

Note that only the "*float* with *trailing* space" tests fail (whereas the "float with *leading* space" tests pass, and all the "*int*" tests pass).

Mini test harness: https://twigfiddle.com/6angrk

### PR DESCRIPTION
**Pull request by guilliamxavier**
Fixes #3345

Refs #2966 (and #3186)

(feel free to discard the "Factorize" commit if you favor performance over maintainability)

### CODE REVIEW

**Comment by fabpot** [comment]
Can you revert the Factorize commit?

**Comment by guilliamxavier** [comment]
@fabpot: Done.

**Review by yorickgirard — APPROVED** [review]

File: tests/Extension/CoreTest.php [hunk 1]
```diff
@@ -306,6 +306,12 @@ public function provideCompareCases()
             [-1, 42, 'abc42'],
             [-1, 0, 'abc42'],
 
+            [0, 42.0, '   42.0'],
+            [0, 42.0, '42.0   '],
+            [-1, 42.0, '42.0abc'],
```
Comment (fabpot) [inline tests/Extension/CoreTest.php:311]: PHP 8 returns 0

File: tests/Extension/CoreTest.php [hunk 2]
```diff
@@ -306,6 +306,12 @@ public function provideCompareCases()
...
+            [-1, 42.0, 'abc42.0'],
+            [-1, 0.0, 'abc42.0'],
```
Comment (fabpot) [inline tests/Extension/CoreTest.php:313]: PHP 8 returns 0

Comment (guilliamxavier) [reply tests/Extension/CoreTest.php:313]: See my answer above

File: tests/Extension/CoreTest.php (hunk 1 above)
Comment (guilliamxavier) [reply tests/Extension/CoreTest.php:311]: @fabpot: But that's unrelated to this PR. Indeed, https://github.com/php/php-src/pull/3886 hasn't been merged (yet), so several _existing_ tests currently return a different result (https://3v4l.org/dX6Q9/rfc#output).

**Comment by fabpot** [comment]
Thank you @guilliamxavier.

File: src/Extension/CoreExtension.php [hunk 3]
```diff
@@ -971,16 +971,18 @@ function twig_compare($a, $b)
...
 
-        return (float) $a <=> $b;
+        return $a <=> (float) $b;
     }
-    if (\is_float($b) && \is_string($a)) {
+    if (\is_string($a) && \is_float($b)) {
         if (is_nan($b)) {
             return 1;
         }
+        $a = trim($a);
```
Comment (stof) [inline src/Extension/CoreExtension.php:985]: wouldn't this trimming cause issue when entering this `!is_numeric($a)` and comparing strings ? Shouldn't we compare the original string then ?

Comment (guilliamxavier) [reply src/Extension/CoreExtension.php:985]: @stof: I think you are right and there was already the problem for `int <=> string` above (see https://3v4l.org/RIUI5). Open a new issue/PR?

Comment (guilliamxavier) [reply src/Extension/CoreExtension.php:985]: @stof: See #3352
