### PR TITLE
changed the way we store template source in template classes

### LINKED ISSUE #2011: Issues with Twig_Template::getSource()
How to reproduce:

  * Install the Symfony Demo app (`$ symfony demo`)
  * Browse any page (e.g. `/en/blog/`)
  * Click on the `Show code` button
  * **ERROR** Twig code is empty
  * Reload the page and click again on the `Show code` button
  * **FIXED** Twig code is displayed

@stof thinks this is caused *"because Twig does not load the cache file but evals the code when the cache does not exist yet"*. More details: https://github.com/symfony/symfony-demo/issues/224

### PR DESCRIPTION
**Pull request by fabpot**
In #1807 and #1813, we added a way to get the original template source code from a template. This PR greatly simplifies the approach by removing all the black magic :)

This should also fix #2011

ping @nicolas-grekas

### CODE REVIEW

File: lib/Twig/Template.php [hunk 1]
```diff
@@ -321,33 +321,6 @@ public function getBlocks()
     }
 
     /**
-     * Returns the template source code.
-     *
-     * @return string|null The template source code or null if it is not available
-     */
-    public function getSource()
```
Comment (stof) [inline lib/Twig/Template.php]: ``getSource`` should still be defined in this class (to be overwritten by child classes), to make it part of the ``Twig_Template`` API (and to make it part of the blacklisted method names when generating methods dynamically in compiled templates).

In Twig 1.x, we should make it concrete (returning an empty string). In Twig 2.x, it can become an abstract method

File: lib/Twig/TokenStream.php [hunk 2]
```diff
@@ -21,16 +21,20 @@ class Twig_TokenStream
     protected $current = 0;
     protected $filename;
 
+    private $source;
+
     /**
      * Constructor.
      *
      * @param array  $tokens   An array of tokens
      * @param string $filename The name of the filename which tokens are associated with
```
Comment (stof) [inline lib/Twig/TokenStream.php]: should be changed to ``string|null`` here too

File: lib/Twig/Template.php (hunk 1 above)
Comment (fabpot) [inline lib/Twig/Template.php]: Not sure why we need to make it concrete in Twig 1.x.

File: lib/Twig/TokenStream.php (hunk 2 above)
Comment (fabpot) [inline lib/Twig/TokenStream.php]: fixed

File: lib/Twig/Template.php (hunk 1 above)
Comment (fabpot) [inline lib/Twig/Template.php]: I mean, I understand the BC concern, but I don't think we need to care about it in this case. Nobody is expected to replace `Twig_Node_Module` in such a drastic way. Am I missing something?

Comment (fabpot) [inline lib/Twig/Template.php]: By the way, I added `getDebugInfo()`, which was not there (see #2132).

Comment (stof) [inline lib/Twig/Template.php]: Do we know whether some people are doing crazy things by implementing a child class of Twig_Template by hand ? We probably don't care about supporting it though

Comment (fabpot) [inline lib/Twig/Template.php]: To be on the safe side, I've made it concrete in 1.x and abstract in 2.0

Comment (emodric) [inline lib/Twig/Template.php]: > Do we know whether some people are doing crazy things by implementing a child class of Twig_Template by hand ? We probably don't care about supporting it though

To reply to @stof's question: Yes, eZ Platform does it in their code to support integration with legacy version which used custom templating engine.

https://github.com/ezsystems/LegacyBridge/blob/master/mvc/Templating/Twig/Template.php

Comment (stof) [inline lib/Twig/Template.php]: @fabpot ``getDebugInfo`` should also be concrete in 1.x then

**Comment by mvrhov** [comment]
@fabpot Do we need the source in production ready templates? E.g when not in development mode.
IMO this pollutes the OPcache string table.

**Comment by fabpot** [comment]
@mvrhov see #2164
