### PR TITLE
Remove optimization as it's not compatible with Symfony cache system

### LINKED ISSUE #2243: Using twig_call_method.php is not compatible with class cache
Using the latest twig master with the Symfony TwigBundle produces this error 
Fatal error: Symfony\Component\ClassLoader\ClassCollectionLoader::main(): Failed opening required '/Users/davidstone/cbsi/gamespot/app/cache/dev/twig_call_method.php' 

This was introduced in https://github.com/twigphp/Twig/commit/bdbfb151115be4eea22e96abd4fd01aa385516aa#diff-8a1ffef1db834d4f5fa55d72a2f43894R14
and happens because the contents of the class file is copied into classes.php  but not the file twig_call_method.php. 

I recommend we remove twig_call_method.php and use only call_user_func_array in the 1.x branch and use $object->$method(...$arguments); in the 2.0 branch since it requires php 5.6.
I would guess the extra function call to twig_call_method() counteracts any performance benefit the new ... language construct provides.

### PR DESCRIPTION
**Pull request by fabpot**
fixes #2243

@nicolas-grekas Instead of fixing Symfony cache system (which will only happen in a new patch release), I propose to revert these changes. It means no optimization for Twig 1.x, but the optimization is the default in Twig 2.0. So, I don't think this is a big deal.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
would be great to still loo at the Symfony patch system though, as it still means there is a bug in it

File: lib/Twig/Template.php [hunk 1]
```diff
@@ -10,10 +10,6 @@
  * file that was distributed with this source code.
  */
 
-if (PHP_VERSION_ID >= 50600) {
-    require_once __DIR__.'/twig_call_method.php';
```
Comment (stof) [inline lib/Twig/Template.php]: on a side note, Twig 1.x advocates 5.2.7 as min PHP version, which was also broken here

**Comment by nicolas-grekas** [comment]
I don't think there is any bug in Symfony. Inlining works for most classes, not for all of them? => don't use the feat when it doesn't work. Straighforward :)

File: lib/Twig/Template.php (hunk 1 above)
Comment (nicolas-grekas) [inline lib/Twig/Template.php]: It wasn't broken: the `if` statement guards from 5.2 failures about `__DIR__`

**Comment by nicolas-grekas** [comment]
BTW, the workaround here would be easy on the 1.x branch: just turn the function into a static method.

**Comment by stof** [comment]
@nicolas-grekas the inlining should be rewriting ``__DIR__``, or forbid inlining such classes. but it should not inline them and break the path silently

File: lib/Twig/Template.php (hunk 1 above)
Comment (stof) [inline lib/Twig/Template.php]: hmm, undefined constants are indeed fine in non-executed paths. I forgot that

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/20455/files#r87772488
