### PR TITLE
Deprecate the possibility to define a block in a non-capturing block from a child template

### LINKED ISSUE #351: {% if true%}{% block ... %}{%endif%}
Hey,

i posted this issue on the mailingliste, but I didn't get any response. I am not sure wether I understand all ideas behind twig but I think this is a bug:

I tried the following and it doesn't work the way I wanted it to work:
{% if type == 0 %}
    {% block menuHandbooks %}currentmenu{% endblock %}
{% endif %}
{% if type == 1 %}
    {% block menuDocuments %}currentmenu{% endblock %}
{% endif %}
{% if type == 2 %}
    {% block menuBetProgram %}currentmenu{% endblock %}
{% endif %}

Is it intended, that all conditions are true? I had a template which was inherited {% extends '::admin.html.twig' %}
and with the above example, the template gets his own body.

The idea is to mark the current page in the menu.

I rebuild it this way and now it works:
{% block menuHandbooks %}
    {% if type == 0 %}currentmenu{% endif %}
{% endblock %}

{% block menuDocuments %}
    {% if type == 1 %}currentmenu{% endif %}
{% endblock %}

{% block menuBetProgram %}
{% if type == 2 %}currentmenu{% endif %}
{% endblock %}

Best regards
Fabian

P.S. Part from the admin.html.twig:
<li class="menu"><a class="{% block menuNews %}{% endblock %}" href="{{path("news_admin")}}">Nachrichten</a></li>
<li class="menu"><a class="{% block menuDocuments %}{% endblock %}" href="{{path("document_admin")}}">Dokumente</a></li>
<li class="menu"><a class="{% block menuHandbooks %}{% endblock %}" href="{{path("handbook_admin")}}">Handbücher</a></li>
<li class="menu"><a class="{% block menuVideos %}{% endblock %}" href="{{path("videos_admin")}}">Lernvideos</a></li>

### PR DESCRIPTION
**Pull request by fabpot**
fixes #351, #541, #703, #988, #1639, #1685, #2393

One recurring issue (see the probably non-exhaustive list of issues references above) is a misunderstanding of how blocks work in a child template.

For instance, there is no way to define a `block` conditionally:

```twig
{% extends "layout" %}

{% if ... %}
    {% block content %}
        ...
    {% endblock %}
{% endif %}
```

And wrapping a `block` definition with a `spaceless` tag does not work:

```twig
{% extends "layout" %}

{% spaceless %}
    {% block content %}
        ...
    {% endblock %}
{% endspaceless %}
```

The issue is that the above templates compile just fine, but not in a way people expect. Basically, the condition would be empty.

Interestingly enough, wrapping a `block` definition might be useful/work as expected when used with "capturing" tags like `set`:

```twig
{% extends "layout" %}

{% set content %}
    {% block content %}
        ...
    {% endblock %}
{% endset %}
```

Not sure if that's useful, but here, the `block` tag will serve as the blog definition AND it will also be displayed in place. I would not recommend such usages.

This pull request deprecates the cases where the compiled template would never reflect the developer intent, but keeps the "working" scenarii as is.

I've been trying to fix that issue for **years**. Very happy to have found a simple solution without breaking anything that worked fine.

### CODE REVIEW

File: lib/Twig/Parser.php [hunk 1]
```diff
@@ -328,17 +328,30 @@ private function filterBodyNodes(Twig_Node $node)
...
+            // a "block" tag in such a node will serve as a block definition AND be displayed in place as well
             return $node;
         }
 
+        // "block" tags that are not captured (see above) are only used for defining
+        // the content of the block. In such a case, nesting it does not work as
+        // expected as the definition is not part of the default template code flow.
+        if ($nested && $node instanceof Twig_Node_BlockReference) {
+            //throw new Twig_Error_Syntax('A block definition cannot be nested under non-capturing nodes.', $node->getTemplateLine(), $this->stream->getSourceContext());
+            @trigger_error('Nesting a block definition under a non-capturing node is deprecated since version 2.5.0 and will become a syntax error in 3.0.', E_USER_DEPRECATED);
```
Comment (stof) [inline lib/Twig/Parser.php]: should it mention the template name, to know where this can be fixed ? the 3.x exception will have the location, but this message does not

File: lib/Twig/Test/IntegrationTestCase.php [hunk 2]
```diff
@@ -176,7 +178,14 @@ protected function doIntegrationTest($file, $message, $condition, $templates, $e
             $p->setAccessible(true);
             $p->setValue($twig, '__TwigTemplate_'.hash('sha256', uniqid(mt_rand(), true), false).'_');
 
+            $deprecations = array();
             try {
+                set_error_handler(function ($type, $msg) use (&$deprecations) {
+                    if (E_USER_DEPRECATED === $type) {
+                        $deprecations[] = $msg;
+                    }
```
Comment (stof) [inline lib/Twig/Test/IntegrationTestCase.php]: the original error handler should be called for any other error, to make the rendering fail. Otherwise, this is equivalent to silencing all non-deprecation errors in tests (defeating the goal of the test)

File: lib/Twig/Parser.php (hunk 1 above)
Comment (fabpot) [reply lib/Twig/Parser.php]: done

File: lib/Twig/Test/IntegrationTestCase.php (hunk 2 above)
Comment (fabpot) [reply lib/Twig/Test/IntegrationTestCase.php]: fixed

**Review by stof — APPROVED** [review]
