### PR TITLE
fixed implementation of Null cache

### LINKED ISSUE #1832: Twig_Null_Cache is oddly implemented
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Null.php uses write() to load the template and load() then just does nothing.

This is kinda problematic if you think about implementing a generic chain of cache backends. There you ideally want to iterate over all of them on write() and just dump the content.

What about adding a hashmap in write() and using that to load the compiled filein load()

### PR DESCRIPTION
**Pull request by fabpot**
fixes #1832

### CODE REVIEW

File: lib/Twig/Cache/Null.php [hunk 1]
```diff
@@ -45,6 +47,9 @@ public function write($key, $content)
      */
     public function load($key)
     {
+        eval('?>'.$this->buffer[$key]);
```
Comment (dawehner) [inline lib/Twig/Cache/Null.php]: Does twig provide any protection against loading it twice already? In case yes, this looks basically how I expect it to look like. Thank you a lot for the very quick response!

File: lib/Twig/Cache/Null.php [hunk 2]
```diff
@@ -16,12 +16,14 @@
  */
 class Twig_Cache_Null implements Twig_CacheInterface
 {
+    private $buffer = array();
```
Comment (dawehner) [inline lib/Twig/Cache/Null.php]: Do you use now short array syntax, as you require PHP 5.5?

Comment (fabpot) [inline lib/Twig/Cache/Null.php]: Nope, this is 1.x, still supporting older versions of PHP. But anyway, I don't plan to migrate to the new short array syntax, mainly because I'm going to maintain both 1.x and 2.x in parallel, so ease of merge is a must.

File: lib/Twig/Cache/Null.php (hunk 1 above)
Comment (fabpot) [inline lib/Twig/Cache/Null.php]: Twig does prevent loading the same template twice (same being a template with the same class name). So, I think this code is safe, except if you are doing very weird things I suppose.

**Comment by stof** [comment]
:+1:

**Comment by LionsAd** [comment]
This looks good to me.
