### PR TITLE
Fix the "filter" filter when the argument is \Traversable but does not implement \Iterator

### LINKED ISSUE #3015: ext-ds Set not supported by the new `filter` filter
We use `ext-ds` and since the `if` condition on `for` was deprecated in Twig 2.10.0, we moved to `filter` tag with arrow functions.

When trying to use the filter on `Ds\Set`, it crashes with:
> CallbackFilterIterator::__construct() must implement interface Iterator, instance of Ds\Set given

This is the (simplified) template code:
```twig
{% for error in errors|filter(error => constant('ERRORS', item)[error] is defined) %}
    {{ constant('ERRORS', item)[error]|trans }}
{% endfor %}
```
The `errors` variable is instance of `Ds\Set`.

Since this was working before, I think that either `Ds\Set` should be supported or even anything implementing `\Traversable`.

### PR DESCRIPTION
**Pull request by fabpot**
close #3015, closes #3016

### CODE REVIEW

File: src/Extension/CoreExtension.php [hunk 1]
```diff
@@ -1686,21 +1686,30 @@ function twig_array_batch($items, $size, $fill = null, $preserveKeys = true)
...
-    while ($array instanceof \IteratorAggregate) {
-        $array = $array->getIterator();
-    }
+        // some internal PHP classes are \Traversable but do not implement \Iterator
+        if ($array instanceof \Iterator) {
+            return new \CallbackFilterIterator($array, $arrow);
+        }
 
-    return new \CallbackFilterIterator($array, $arrow);
+        throw new RuntimeException('The "filter" filter argument only supports objects implementing \Iterator; upgrade to PHP 5.5+.');
```
Comment (enumag) [inline src/Extension/CoreExtension.php:1709]: I think you could use [IteratorIterator](https://www.php.net/manual/en/class.iteratoriterator.php) to change Traversable into Iterator on PHP 5.4. Also you should be able to get rid of the `while ($array instanceof \IteratorAggregate) {` that way.

Comment (fabpot) [reply src/Extension/CoreExtension.php:1709]: You're right, much better, see #3021
