### PR TITLE
Fix "batch filter clobbers array keys when fill parameter is used "

### LINKED ISSUE #2568: batch filter clobbers array keys when fill parameter is used
batch filter clobbers array keys when fill parameter is used

On the last array chunk if there are fewer keys than the chuck size when the batch filter fills in the missing value it re-numbers the array keys.

### PR DESCRIPTION
**Pull request by fabpot**
closes #2568

### CODE REVIEW

File: src/Extension/CoreExtension.php [hunk 1]
```diff
@@ -1638,23 +1638,22 @@ function twig_constant_is_defined($constant, $object = null)
...
 
-    if (null !== $fill && !empty($result)) {
+    if (null !== $fill && $result) {
         $last = \count($result) - 1;
         if ($fillCount = $size - \count($result[$last])) {
-            $result[$last] = array_merge(
-                $result[$last],
-                array_fill(0, $fillCount, $fill)
-            );
+            foreach (array_fill(0, $fillCount, $fill) as $v) {
```
Comment (stof) [inline src/Extension/CoreExtension.php]: do we actually need to use `array_fill` to generate an array here ? This is a loop from `0` to `$fillCount`, putting `$fill` in the array.

Comment (fabpot) [reply src/Extension/CoreExtension.php]: yep, forgot to change that.

Comment (fabpot) [reply src/Extension/CoreExtension.php]: done
