### PR TITLE
Fix 'ignore missing' when used on an 'embed' tag

### LINKED ISSUE #3085: 'ignore missing' does not ignore missing templates
This appears like it might well be a Twig bug, on my local, using the version on my branch (v1.38.4 ) adding a made up template to the homepage:

{% set x = 'bad' %}
{% embed x ~ 'ger.twig' ignore missing %}
{% endembed %}

Does not error, removing 'ignore missing' causes it to error…

Upgrading twig/twig (v1.38.4 => v1.42.1)

At which point the ignore missing directive appears to no longer work and the above test fails 

Twig\Error\LoaderError thrown with message "Unable to find template

### PR DESCRIPTION
**Pull request by fabpot**
Closes #3085

### CODE REVIEW

File: tests/Node/IncludeTest.php [hunk 1]
```diff
@@ -80,9 +80,10 @@ public static function provideTests(): iterable
 // line 1
 \$__internal_%s = null;
 try {
-    \$__internal_%s =     \$this->loadTemplate("foo.twig", null, 1);
+    \$__internal_%s = \$this->loadTemplate("foo.twig", null, 1);
 } catch (LoaderError \$e) {
     // ignore missing template
+    \$__internal_%s = null;
```
Comment (stof) [inline tests/Node/IncludeTest.php:86]: this seems useless as it is already assigned before the try/catch. Why do we need it ?

Comment (fabpot) [reply tests/Node/IncludeTest.php:86]: The EmbedNode extends this one and there the template loading doesn’t fail. It fails when trying to load the parent. So we need to reset the variable here for this use case.

Comment (ruudk) [reply tests/Node/IncludeTest.php:86]: Removed the assign before the try/catch here: 
- https://github.com/twigphp/Twig/pull/4346
